project:
  type: website

website:
  title: Byte Coders
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO526-DataViz/project-01
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
    logo: images\logo.webp
  favicon: images\logo.webp
    

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
